#!/bin/sh
# =============================================================================
# email_alerts.sh — Email Alert Library for QManager
# =============================================================================
# Sourced by qmanager_poller and CGI scripts. Detects prolonged internet
# downtime and sends a recovery email (with downtime details) via msmtp
# once connectivity is restored.
#
# Dependencies: jq, msmtp, qlog_* functions (optional)
# Install location: /usr/lib/qmanager/email_alerts.sh
#
# Global variables used from poller:
#   Read: conn_internet_available ("true"/"false"/"null")
#
# Config:  /etc/qmanager/email_alerts.json
# Log:     /tmp/qmanager_email_log.json (NDJSON, max 100 entries)
# msmtp:   /etc/qmanager/msmtprc (generated by CGI on save)
# Reload:  /tmp/qmanager_email_reload (flag file, touched by CGI)
# =============================================================================

[ -n "$_EMAIL_ALERTS_LOADED" ] && return 0
_EMAIL_ALERTS_LOADED=1

# --- Constants ---------------------------------------------------------------
_EA_CONFIG="/etc/qmanager/email_alerts.json"
_EA_MSMTP_CONFIG="/etc/qmanager/msmtprc"
_EA_LOG_FILE="/tmp/qmanager_email_log.json"
_EA_RELOAD_FLAG="/tmp/qmanager_email_reload"
_EA_MAX_LOG=100
_EA_RECOVERY_PIDFILE="/tmp/qmanager_email_send.pid"

# Detect msmtp binary — Entware installs to /opt/bin which is not in the
# poller's PATH. Check common locations so both CGI and daemon contexts work.
_EA_MSMTP_BIN=""
for _p in /opt/bin/msmtp /usr/bin/msmtp; do
    if [ -x "$_p" ]; then
        _EA_MSMTP_BIN="$_p"
        break
    fi
done

# --- State (populated by email_alerts_init / _ea_read_config) ----------------
_ea_enabled="false"
_ea_sender=""
_ea_recipient=""
_ea_app_password=""
_ea_threshold_minutes=5

# --- Downtime tracking (poller runtime only) ---------------------------------
_ea_was_down="false"
_ea_downtime_start=0

# =============================================================================
# _ea_read_config — Read settings from config JSON
# =============================================================================
_ea_read_config() {
    if [ ! -f "$_EA_CONFIG" ]; then
        _ea_enabled="false"
        return 1
    fi

    _ea_enabled=$(jq -r '(.enabled) | if . == null then "false" else tostring end' "$_EA_CONFIG" 2>/dev/null)
    _ea_sender=$(jq -r '.sender_email // ""' "$_EA_CONFIG" 2>/dev/null)
    _ea_recipient=$(jq -r '.recipient_email // ""' "$_EA_CONFIG" 2>/dev/null)
    _ea_app_password=$(jq -r '.app_password // ""' "$_EA_CONFIG" 2>/dev/null)
    _ea_threshold_minutes=$(jq -r '.threshold_minutes // 5' "$_EA_CONFIG" 2>/dev/null)

    # Validate
    if [ "$_ea_enabled" != "true" ]; then
        _ea_enabled="false"
        return 0
    fi
    if [ -z "$_ea_sender" ] || [ -z "$_ea_recipient" ] || [ -z "$_ea_app_password" ]; then
        _ea_enabled="false"
        return 1
    fi
    return 0
}

# =============================================================================
# email_alerts_init — Called once at poller startup
# =============================================================================
email_alerts_init() {
    _ea_read_config
    if [ "$_ea_enabled" = "true" ]; then
        qlog_info "Email alerts enabled: sender=$_ea_sender recipient=$_ea_recipient threshold=${_ea_threshold_minutes}m"
    else
        qlog_info "Email alerts disabled or not configured"
    fi
}

# =============================================================================
# check_email_alert — Called every poll cycle after detect_events
# =============================================================================
# Reads conn_internet_available (global from poller).
# Tracks downtime start, sends recovery email when internet returns after
# a downtime that exceeded the configured threshold.
# =============================================================================
check_email_alert() {
    # No alerts during scheduled low power mode
    [ -f "/tmp/qmanager_low_power_active" ] && return 0

    # Check for reload flag (CGI saved new settings)
    if [ -f "$_EA_RELOAD_FLAG" ]; then
        rm -f "$_EA_RELOAD_FLAG"
        _ea_read_config
        qlog_info "Email alerts config reloaded: enabled=$_ea_enabled"
    fi

    # Skip if disabled or not fully configured
    [ "$_ea_enabled" != "true" ] && return 0

    # Null/stale ping state: skip ONLY if not already tracking downtime.
    # If we're already tracking, stale data likely means the poller was stuck
    # on AT commands during an outage — keep the downtime timer running.
    if [ "$conn_internet_available" = "null" ] || [ -z "$conn_internet_available" ]; then
        [ "$_ea_was_down" != "true" ] && return 0
        # Already tracking downtime — keep going (don't reset)
        return 0
    fi

    if [ "$conn_internet_available" = "false" ]; then
        # Internet is down — record start time if not already tracking
        if [ "$_ea_was_down" != "true" ]; then
            _ea_downtime_start=$(date +%s)
            _ea_was_down="true"
            qlog_debug "Email alerts: downtime tracking started at $_ea_downtime_start"
        fi

    elif [ "$conn_internet_available" = "true" ] && [ "$_ea_was_down" = "true" ]; then
        # Internet recovered — check if downtime exceeded threshold
        local now
        local duration
        local threshold_secs
        now=$(date +%s)
        duration=$((now - _ea_downtime_start))
        threshold_secs=$((_ea_threshold_minutes * 60))

        qlog_info "Email alerts: recovery detected — measured downtime=${duration}s, threshold=${threshold_secs}s"

        if [ "$duration" -ge "$threshold_secs" ]; then
            qlog_info "Email alerts: threshold exceeded, dispatching recovery email"
            _ea_send_recovery_email_async "$_ea_downtime_start" "$duration"
        else
            qlog_info "Email alerts: downtime ${duration}s < threshold ${threshold_secs}s — skipped (ping debounce eats ~25s)"
        fi

        # Reset tracking
        _ea_was_down="false"
        _ea_downtime_start=0
    fi
}

# =============================================================================
# _ea_send_recovery_email_async — Background variant for the poll loop
# =============================================================================
# The poller calls this so the main loop never blocks on the 30s stabilize
# delay or the msmtp SMTP I/O. Single-flight via _EA_RECOVERY_PIDFILE: if a
# previous worker is still running, drop this one (the previous send will
# either succeed or be logged as failed — either way, do not stack).
_ea_send_recovery_email_async() {
    local start_epoch="$1"
    local duration_secs="$2"

    # Single-flight check
    if [ -f "$_EA_RECOVERY_PIDFILE" ]; then
        local _old_pid
        _old_pid=$(cat "$_EA_RECOVERY_PIDFILE" 2>/dev/null)
        if [ -n "$_old_pid" ] && [ -d "/proc/$_old_pid" ]; then
            qlog_warn "Email alerts: previous recovery send still in flight (pid=$_old_pid), skipping new dispatch"
            return 0
        fi
        rm -f "$_EA_RECOVERY_PIDFILE"
    fi

    # Fork the send. Closing stdin/stdout/stderr lets systemd reap the child
    # without keeping a journal pipe open. We capture the worker's PID via
    # $! after backgrounding (NOT $$ inside the subshell — that resolves to
    # the parent poller's PID and would create a permanent lockout if the
    # worker is hard-killed). The stale-file cleanup at the top of this
    # function already handles orphans, so no EXIT trap is needed.
    (
        _ea_send_recovery_email "$start_epoch" "$duration_secs"
    ) </dev/null >/dev/null 2>&1 &
    local _ea_worker_pid=$!
    echo "$_ea_worker_pid" > "$_EA_RECOVERY_PIDFILE" 2>/dev/null
}

# =============================================================================
# _ea_send_recovery_email — Format and send recovery notification
# =============================================================================
_ea_send_recovery_email() {
    local start_epoch="$1"
    local duration_secs="$2"

    # Format start time
    # BusyBox date supports -d @epoch on most builds; fall back to awk strftime
    # (date -r is macOS/FreeBSD only — not available on BusyBox)
    local start_time
    start_time=$(date -d "@$start_epoch" "+%Y-%m-%d %H:%M:%S" 2>/dev/null) || \
        start_time=$(awk "BEGIN{print strftime(\"%Y-%m-%d %H:%M:%S\",$start_epoch)}" 2>/dev/null) || \
        start_time="$start_epoch"

    # Format duration
    local dur_text
    dur_text=$(_ea_format_duration "$duration_secs")

    # Build HTML email
    local html
    html=$(_ea_build_recovery_html "$start_time" "$dur_text" "$_ea_threshold_minutes")

    # Send with retry — DNS and SMTP are not ready immediately after recovery.
    # Wait for the connection to stabilize before the first send attempt.
    local trigger_text="Connection recovered (down ${dur_text})"
    local attempt=0
    local max_attempts=3
    local retry_delay=15
    local stabilize_delay=30

    qlog_info "Email alerts: waiting ${stabilize_delay}s for connection to stabilize..."
    sleep "$stabilize_delay"

    while [ "$attempt" -lt "$max_attempts" ]; do
        attempt=$((attempt + 1))

        if [ "$attempt" -gt 1 ]; then
            qlog_info "Email alerts: retry $attempt/$max_attempts after ${retry_delay}s..."
            sleep "$retry_delay"
        fi

        if _ea_do_send "Connection Recovered" "$html"; then
            _ea_log_event "$trigger_text" "sent" "$_ea_recipient"
            return
        fi

        qlog_warn "Email alerts: send attempt $attempt/$max_attempts failed"
    done

    qlog_error "Email alerts: all $max_attempts send attempts failed"
    _ea_log_event "$trigger_text" "failed" "$_ea_recipient"
}

# =============================================================================
# _ea_send_test_email — Send a test email (called by CGI)
# =============================================================================
_ea_send_test_email() {
    local html
    html=$(_ea_build_test_html)

    if _ea_do_send "Test Alert" "$html"; then
        _ea_log_event "Test email" "sent" "$_ea_recipient"
        return 0
    else
        _ea_log_event "Test email" "failed" "$_ea_recipient"
        return 1
    fi
}

# =============================================================================
# _ea_do_send — Core msmtp send function
# =============================================================================
_ea_do_send() {
    local subject="$1"
    local html_body="$2"

    if [ -z "$_EA_MSMTP_BIN" ] || [ ! -x "$_EA_MSMTP_BIN" ]; then
        qlog_error "Email alerts: msmtp not installed"
        return 1
    fi

    if [ ! -f "$_EA_MSMTP_CONFIG" ]; then
        qlog_error "Email alerts: msmtp config not found at $_EA_MSMTP_CONFIG"
        return 1
    fi

    {
        printf "From: %s\r\n" "$_ea_sender"
        printf "To: %s\r\n" "$_ea_recipient"
        printf "Subject: [QManager] %s\r\n" "$subject"
        printf "MIME-Version: 1.0\r\n"
        printf "Content-Type: text/html; charset=UTF-8\r\n"
        printf "\r\n"
        printf "%s" "$html_body"
    } | "$_EA_MSMTP_BIN" -C "$_EA_MSMTP_CONFIG" "$_ea_recipient" 2>/tmp/msmtp_last_err.log

    local rc=$?
    if [ $rc -eq 0 ]; then
        qlog_info "Email alerts: email sent successfully to $_ea_recipient"
    else
        local err_detail
        err_detail=$(cat /tmp/msmtp_last_err.log 2>/dev/null)
        qlog_error "Email alerts: msmtp failed (rc=$rc): $err_detail"
    fi
    return $rc
}

# =============================================================================
# _ea_log_event — Append entry to NDJSON log file
# =============================================================================
_ea_log_event() {
    local trigger="$1"
    local status="$2"
    local recipient="$3"
    local ts
    ts=$(date "+%Y-%m-%d %H:%M:%S")

    jq -n -c \
        --arg ts "$ts" \
        --arg trigger "$trigger" \
        --arg status "$status" \
        --arg recipient "$recipient" \
        '{timestamp: $ts, trigger: $trigger, status: $status, recipient: $recipient}' \
        >> "$_EA_LOG_FILE"

    # Trim to max entries
    local count
    count=$(wc -l < "$_EA_LOG_FILE" 2>/dev/null || echo 0)
    if [ "$count" -gt "$_EA_MAX_LOG" ]; then
        local tmp="${_EA_LOG_FILE}.tmp"
        if tail -n "$_EA_MAX_LOG" "$_EA_LOG_FILE" > "$tmp" 2>/dev/null; then
            mv "$tmp" "$_EA_LOG_FILE" 2>/dev/null || rm -f "$tmp"
        else
            rm -f "$tmp"
        fi
    fi
}

# =============================================================================
# _ea_format_duration — Convert seconds to human-readable string
# =============================================================================
_ea_format_duration() {
    local secs="$1"
    local hours
    local mins
    local remaining

    hours=$((secs / 3600))
    remaining=$((secs % 3600))
    mins=$((remaining / 60))
    remaining=$((remaining % 60))

    if [ "$hours" -gt 0 ]; then
        printf "%dh %dm %ds" "$hours" "$mins" "$remaining"
    elif [ "$mins" -gt 0 ]; then
        printf "%dm %ds" "$mins" "$remaining"
    else
        printf "%ds" "$remaining"
    fi
}

# =============================================================================
# HTML Email Templates
# =============================================================================
# Table-based layout with inline styles for maximum email client compatibility.
# No external resources — fully self-contained.
# =============================================================================

_EA_COLOR_PRIMARY="#4338ca"
_EA_COLOR_SUCCESS="#22c55e"
_EA_COLOR_BG="#f4f4f5"
_EA_COLOR_WHITE="#ffffff"
_EA_COLOR_TEXT="#18181b"
_EA_COLOR_MUTED="#71717a"
_EA_FONT="'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif"

# --- Shared wrapper (header + footer) ----------------------------------------

_ea_html_header() {
    local subtitle="$1"
    cat <<HTMLEOF
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background-color:${_EA_COLOR_BG};font-family:${_EA_FONT};">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:${_EA_COLOR_BG};padding:32px 16px;">
<tr><td align="center">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:520px;">

<!-- Header -->
<tr><td style="background-color:${_EA_COLOR_PRIMARY};padding:24px 32px;border-radius:10px 10px 0 0;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
  <tr>
    <td style="color:${_EA_COLOR_WHITE};font-size:20px;font-weight:700;letter-spacing:-0.3px;">QManager</td>
  </tr>
  <tr>
    <td style="color:rgba(255,255,255,0.75);font-size:13px;padding-top:4px;">${subtitle}</td>
  </tr>
  </table>
</td></tr>

<!-- Content card -->
<tr><td style="background-color:${_EA_COLOR_WHITE};padding:32px;border-radius:0 0 10px 10px;">
HTMLEOF
}

_ea_html_footer() {
    cat <<HTMLEOF
</td></tr>

<!-- Footer -->
<tr><td style="padding:24px 32px;text-align:center;">
  <p style="margin:0 0 4px;font-size:12px;color:${_EA_COLOR_MUTED};">QManager &middot; Quectel Modem Management</p>
  <p style="margin:0;font-size:11px;color:${_EA_COLOR_MUTED};">You received this because email alerts are enabled on your device.</p>
</td></tr>

</table>
</td></tr></table>
</body>
</html>
HTMLEOF
}

# --- Recovery email -----------------------------------------------------------

_ea_build_recovery_html() {
    local start_time="$1"
    local duration="$2"
    local threshold="$3"

    {
        _ea_html_header "Connection Alert"

        cat <<HTMLEOF
  <!-- Badge -->
  <table role="presentation" cellpadding="0" cellspacing="0"><tr>
    <td style="background-color:${_EA_COLOR_SUCCESS};color:${_EA_COLOR_WHITE};font-size:12px;font-weight:600;padding:4px 12px;border-radius:20px;letter-spacing:0.3px;">RECOVERED</td>
  </tr></table>

  <!-- Headline -->
  <h1 style="margin:16px 0 8px;font-size:18px;font-weight:600;color:${_EA_COLOR_TEXT};">Your connection has been restored</h1>
  <p style="margin:0 0 24px;font-size:14px;color:${_EA_COLOR_MUTED};line-height:1.5;">Your internet connection experienced an outage that exceeded the configured alert threshold.</p>

  <!-- Detail box -->
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:${_EA_COLOR_BG};border-radius:8px;padding:4px 0;">
  <tr>
    <td style="padding:12px 20px;border-bottom:1px solid #e4e4e7;">
      <span style="font-size:12px;color:${_EA_COLOR_MUTED};text-transform:uppercase;letter-spacing:0.5px;">Downtime Started</span><br>
      <span style="font-size:15px;color:${_EA_COLOR_TEXT};font-weight:500;">${start_time}</span>
    </td>
  </tr>
  <tr>
    <td style="padding:12px 20px;border-bottom:1px solid #e4e4e7;">
      <span style="font-size:12px;color:${_EA_COLOR_MUTED};text-transform:uppercase;letter-spacing:0.5px;">Duration</span><br>
      <span style="font-size:15px;color:${_EA_COLOR_TEXT};font-weight:500;">${duration}</span>
    </td>
  </tr>
  <tr>
    <td style="padding:12px 20px;">
      <span style="font-size:12px;color:${_EA_COLOR_MUTED};text-transform:uppercase;letter-spacing:0.5px;">Alert Threshold</span><br>
      <span style="font-size:15px;color:${_EA_COLOR_TEXT};font-weight:500;">${threshold} minutes</span>
    </td>
  </tr>
  </table>

  <p style="margin:24px 0 0;font-size:13px;color:${_EA_COLOR_MUTED};line-height:1.5;">This alert was sent because the outage exceeded your configured threshold of ${threshold} minutes.</p>
HTMLEOF

        _ea_html_footer
    }
}

# --- Test email ---------------------------------------------------------------

_ea_build_test_html() {
    {
        _ea_html_header "Test Notification"

        cat <<HTMLEOF
  <!-- Badge -->
  <table role="presentation" cellpadding="0" cellspacing="0"><tr>
    <td style="background-color:${_EA_COLOR_PRIMARY};color:${_EA_COLOR_WHITE};font-size:12px;font-weight:600;padding:4px 12px;border-radius:20px;letter-spacing:0.3px;">TEST</td>
  </tr></table>

  <!-- Headline -->
  <h1 style="margin:16px 0 8px;font-size:18px;font-weight:600;color:${_EA_COLOR_TEXT};">Your email alert configuration is working</h1>
  <p style="margin:0 0 4px;font-size:14px;color:${_EA_COLOR_MUTED};line-height:1.5;">This was a test email triggered from the QManager dashboard. Your email alert settings are correctly configured and ready to send notifications.</p>

  <p style="margin:20px 0 0;font-size:13px;color:${_EA_COLOR_MUTED};line-height:1.5;">No action is needed.</p>
HTMLEOF

        _ea_html_footer
    }
}
